// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQVgThffgxbLBlHcrnJ30j3-ojg4nJJEQ',
    appId: '1:856105719942:web:465bb88f0a526e2d7ad907',
    messagingSenderId: '856105719942',
    projectId: 'recyclify-1',
    authDomain: 'recyclify-1.firebaseapp.com',
    storageBucket: 'recyclify-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2wFvZCymy7S4BCi_lqXDNsjs01Ui7_lo',
    appId: '1:856105719942:android:a0d2ebed181116cc7ad907',
    messagingSenderId: '856105719942',
    projectId: 'recyclify-1',
    storageBucket: 'recyclify-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpQ_AxNvbPYtGNughZdZryuvOZYQql_gk',
    appId: '1:856105719942:ios:3d02c47f36619fd17ad907',
    messagingSenderId: '856105719942',
    projectId: 'recyclify-1',
    storageBucket: 'recyclify-1.appspot.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpQ_AxNvbPYtGNughZdZryuvOZYQql_gk',
    appId: '1:856105719942:ios:3d02c47f36619fd17ad907',
    messagingSenderId: '856105719942',
    projectId: 'recyclify-1',
    storageBucket: 'recyclify-1.appspot.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQVgThffgxbLBlHcrnJ30j3-ojg4nJJEQ',
    appId: '1:856105719942:web:2413ad03fbdc0e3e7ad907',
    messagingSenderId: '856105719942',
    projectId: 'recyclify-1',
    authDomain: 'recyclify-1.firebaseapp.com',
    storageBucket: 'recyclify-1.appspot.com',
  );
}
